### PR TITLE
Install the library using the corresponding JLL package

### LINKED ISSUE #19: Provide binary dependency with JLL package
To keep up with the times, the FINUFFT dependency should be provided as a JLL created using BinaryBuilder. Contributions welcome!

### PR DESCRIPTION
**Pull request by giordano**
Close #19

### CODE REVIEW

**Comment by giordano** [comment]
Tests passing on all operating systems (including FreeBSD and Windows, never tested before) without having to install Conda nor any compiler :slightly_smiling_face:

**Comment by ludvigak** [comment]
Nice! I'm away from computer for a while, but will merge once I'm back and have tried it myself.

One question though, do we have to disable OpenMP, or could we maybe build FFTW with threading ourselves and ship it in the JLL? 
It would really be a bummer to have FINUFFT run single core only in the Julia interface.

**Comment by giordano** [comment]
> One question though, do we have to disable OpenMP, or could we maybe build FFTW with threading ourselves and ship it in the JLL?

I'm a bit confused by this: FFTW does have threading enabled, and it's used by FFTW.jl.  Isn't it sufficient?

**Comment by ludvigak** [comment]
I'm referring to the comment by @jonas-kr in #19, but maybe I should have a look at the code before I open my mouth. 
In any case, FINUFFT does have a significantly portion of code that is accelerated by threading, outside of the FFT calls sent to FFTW.

**Comment by giordano** [comment]
Can't we simply enable OpenMP in finufft?  I don't understand how FFTW is relevant

**Comment by jonas-kr** [comment]
Actually, I have already created a custom build of the jll with openMP enabled! I do not have much time today, so I will provide an update tomorrow.

**Comment by jonas-kr** [comment]
[Pull request](https://github.com/JuliaPackaging/Yggdrasil/pull/1435) for updated finufft_jll is open and builds successfully on all platforms. The main disadvantage of enabled threading is that finufft uses all available threads by default (despite most x86 CPUs featuring SMT) by default, which can lead to worse performance than the single-threaded scenario. I hope that the new guruInterface_v2 branch is ready for release soon such that it becomes possible to configure the number of threads.

**Comment by MikaelSlevinsky** [comment]
I think you can get around the performance loss of hyper-threading by initializing the library with half the `Sys.CPU_THREADS`

https://github.com/JuliaApproximation/FastTransforms.jl/blob/c68fceb0169d7736a29672c278513bb018c4b608/src/libfasttransforms.jl#L13-L20

**Comment by ludvigak** [comment]
Thanks for the work @giordano and @jonas-kr , it's pretty great to finally have this package dragged into the modern world of jll-packaging =)
Also, sorry for dragging my feet on the merge!

@MikaelSlevinsky @jonas-kr regarding the threading, I think that's mainly due to FINUFFT having been developed for large datasets, and I think/hope that we'll develop some better heuristics for choosing # of threads. Anyway, tinkering with Sys.CPU_THREADS in the interface would risk messing with any such heuristics developed upstream.

**Pull request merged**
