### PR TITLE
Remove redundant checks whereever possible

### PR DESCRIPTION
**Pull request by jkrimmer**
Take care of #46 .

### CODE REVIEW

**Review by ahbarnett — APPROVED** [review]
I am all in favor of simpler code, removing redundancy. I haven't tested this one.

**Comment by ahbarnett** [comment]
FWIW I tested your 3.1.0 now on master, and the tests and examples are all good on my julia 1.7 linux laptop. Thanks for that! Alex

**Comment by ludvigak** [comment]
Sure, no reason not to simplify. Seems to be a merge conflict at the moment though

**Comment by jkrimmer** [comment]
Good point, I will work on the conflicts later today

**Comment by ludvigak** [comment]
Merging stale PR

**Pull request merged**
