### PR TITLE
Infer dtype for finufft_makeplan

### LINKED ISSUE #42: In-place versions nufftndm! require dtype argument for single-precision transforms
The in-place versions nufftndm! do not work for single-precision inputs without explicitly providing the dtype keyword argument whereas the out-of-place variants work just fine:

Out-of-place:
```
julia> using FINUFFT

julia> nj = 1000000;

julia> x = pi*(1 .- 2*rand(Float32, nj));

julia> c = rand(ComplexF32, nj);

julia> ms = 2000000;

julia> tol = 1e-5;

julia> fk = nufft1d1(x, c, 1, tol, ms);
```

In-place:
```
julia> fk = nufft1d1!(x, c, 1, tol, Array{ComplexF32}(undef,ms));
ERROR: MethodError: no method matching finufft_setpts!(::finufft_plan{Float64}, ::Vector{Float32})
Closest candidates are:
  finufft_setpts!(::finufft_plan{T}, ::Array{T}) where T<:Union{Float32, Float64} at C:\Users\mv6955\.julia\packages\FINUFFT\GNqRW\src\guru.jl:159
  finufft_setpts!(::finufft_plan{T}, ::Array{T}, ::Array{T}) where T<:Union{Float32, Float64} at C:\Users\mv6955\.julia\packages\FINUFFT\GNqRW\src\guru.jl:159
  finufft_setpts!(::finufft_plan{T}, ::Array{T}, ::Array{T}, ::Array{T}) where T<:Union{Float32, Float64} at C:\Users\mv6955\.julia\packages\FINUFFT\GNqRW\src\guru.jl:159
  ...
Stacktrace:
 [1] nufft1d1!(xj::Vector{Float32}, cj::Vector{ComplexF32}, iflag::Int64, eps::Float64, fk::Vector{ComplexF32}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ FINUFFT C:\Users\mv6955\.julia\packages\FINUFFT\GNqRW\src\simple.jl:470
 [2] nufft1d1!(xj::Vector{Float32}, cj::Vector{ComplexF32}, iflag::Int64, eps::Float64, fk::Vector{ComplexF32})
   @ FINUFFT C:\Users\mv6955\.julia\packages\FINUFFT\GNqRW\src\simple.jl:458
 [3] top-level scope
   @ REPL[23]:1
```

Using the dtype argument, the problem is resolved:
```
julia> fk = nufft1d1!(x, c, 1, tol, Array{ComplexF32}(undef,ms), dtype=Float32);
```

Wouldn't it make more sense to adapt the in-place function definitions such that they infer the plan-type from the provided-data, e.g., as in
``` 
function nufft1d1!(xj      :: Array{T},
                   cj      :: Array{Complex{T}},
                   iflag   :: Integer, 
                   eps     :: Real,
                   fk      :: Array{Complex{T}};
                   kwargs...) where T <: finufftReal
    valid_setpts(1,1,xj)
    ntrans = valid_ntr(xj,cj)
    (ms, ntrans_fk) = get_nmodes_from_fk(1,fk)

    checkkwdtype(T; kwargs...)
    plan = finufft_makeplan(1,[ms;],iflag,ntrans,eps;**dtype=T**,kwargs...)
    finufft_setpts!(plan,xj)
    finufft_exec!(plan,cj,fk)
    ret = finufft_destroy!(plan)
    check_ret(ret)
end
```

I highlighted the proposed modification with ** **. 

Cheers, Jonas

### PR DESCRIPTION
**Pull request by jkrimmer**
Fixes #42

### CODE REVIEW

**Review by ahbarnett — APPROVED** [review]
I tested locally and it fixes the problem. To be honest I don't understand why `finufft_setpts!` was failing before, or why the plan stage went ok. Julia types confuse me.

Thanks!

**Comment by jkrimmer** [comment]
Before, without providing the dtype argument, the `nufftndm!` methods defaulted to a finufft plan for a double precision transform independent of the provided data. Hence, `finufft_setpts!` threw an error in the MWE since its arguments contained both a double precision plan and single precision data. To resolve the issue, we had to pass the keyword argument `dtype=Float32` explicitly. Now, we automatically infer the type of the plan from the provided data why we do not have to set the `dtype` argument anymore for the in-place transforms. 

Cheers
Jonas

**Comment by ludvigak** [comment]
I actually think we should drop the `dtype` keyword argument from the simple interface entirely, since it doesn't really serve a purpose when the data type is inferred from the input arrays. All `dtype` is used for now is to `assert dtype==T`, but I would argue that we can expect the user to know what they are doing if they are passing F32 arrays.

However, we don't want to be breaking any user code, so if we drop `dtype` from the simple interface then we need to add a deprecation warning (i.e. in `checkkwdtype`) and bump the minor version.

**Comment by ludvigak** [comment]
Nice work! Just one thing: we need a bump of minor version, not patch, so 3.0.2 -> 3.1.0

**Comment by ludvigak** [comment]
Also the README needs an update, but I can do that right away in the branch...

**Comment by jkrimmer** [comment]
Thank you! I just bumped the version number again

**Comment by jkrimmer** [comment]
@ludvigak : Would you mind having a new tag/release? This way, the FINUFFT.jl version provided by the julia package manager will contain this fix.

**Comment by ludvigak** [comment]
Doing it now!

**Pull request merged**
