### PR TITLE
Combined FP/DP interfaces & Guru interface

### PR DESCRIPTION
**Pull request by jonas-kr**
To fix the lack of thread-safety during the first call (see #28 ), I added the Guru interface functions (they are neither exported nor documented). Further, the FP/DP interfaces are now available from the same functions, i.e., there is no additonal 'f' required anymore. 
Since one of the 3D single precision tests failed at least on my system, I increased the tolerance by a factor of 2.

### CODE REVIEW

**Review by ludvigak — CHANGES_REQUESTED** [review]
1. Re. your combining of the FP/DP interfaces, you are actually bypassing Julia's multiple dispatch system when you define the methods with a type parameter `T`, only to then do a `if T <: fftwDouble` switch inside the method.
If you want a unified interface, a much simpler change is to just remove the "f" in the method definitions in `single.jl`, i.e. `nufftf1d1!` -> `nufft1d1!`.
I think this also ends up being clearer code.
For backwards compatibility you can then add `const nufftf1d1! = nufftf1d1!` (with the slightly odd side effect of being able to use  F64 in the methods with F32-names)

2. Why changing `Array` to `StridedArray` everywhere? Is there a benefit?

3. Very nice to have the guru interface. Could you add it in a separate source file that gets included, e.g. `guru.jl`? The file `FINUFFT.jl` is getting pretty bloated as it is. 

4. The guru interface needs unit tests.

**Comment by ludvigak** [comment]
Hey! My apologies for being slow to react on this. I really appreciate your contributions, but it's not every day that I can take the time to sit down and give them a proper review.

**Comment by jonas-kr** [comment]
Hi, thank you very much for your feedback. No worries about being late, good things come to those who wait. Unfortunately, I am super busy these days; hence, I do not expect to introduce further changes within the next two weeks.

1. You are definitely right when it comes to the combined interface. I will revert this change. Your idea of providing backwards compatibility with `const nufftf1d1! = nufftf1d1!` sounds reasonable. Combined with a deprecation warning (?), the possiblity to use F64 data with the F32 methods would not really matter, wouldn't it?
2. The restriction to `StridedArray` allows to pass array views to finufft, which might be useful.
3. Of course!
4. ... and at least some kind of documentation. I will take care of this issue as well.

**Comment by lu1and10** [comment]
> Hi, thank you very much for your feedback. No worries about being late, good things come to those who wait. Unfortunately, I am super busy these days; hence, I do not expect to introduce further changes within the next two weeks.
> 
> 1. You are definitely right when it comes to the combined interface. I will revert this change. Your idea of providing backwards compatibility with `const nufftf1d1! = nufftf1d1!` sounds reasonable. Combined with a deprecation warning (?), the possibility to use F64 data with the F32 methods would not really matter, wouldn't it?
> 2. The restriction to `StridedArray` allows to pass array views to finufft, which might be useful.
> 3. Of course!
> 4. ... and at least some kind of documentation. I will take care of this issue as well.

Hi @jonas-kr @ludvigak , it is great to have the guru interfaces in Julia, thanks a lot! Alex and I did not notice you are working on the Julia interface too, we were also working on that. I prefer most of the changes, I look at the first version of @jonas-kr 's pull request, I think the code is great and I made some changes in my own fork, the following link contains the draft code you can take a lot.
https://github.com/lu1and10/FINUFFT.jl/blob/guru_v2/src/FINUFFT.jl


Basically, I follow Alex's Matlab and python interface in finufft master branch. 
1. The simple interfaces(nufft*d*) calls the Julia guru calls instead of calling the C++ side simple interfaces, this may be more maintainable if the simple interfaces change in C++, and calling the guru calls can add the multiple transfer(ntrans) functionality for the simple interfaces(nufft*d*).
2. There is an extra field in opts called is_double(we can change the name later, maybe to opts.eltype) to get from user if it's double precision or single precision calls, this also follows Matlab and Python interfaces.
3.  I add both finufft_exec! and finufft_exec for output passed in by user or output allocation needed, and a plan struct in Julia is maintained to remember the output array sizes.
4.  All these functions includes some sort of size checking to make sure input/output array sizes are consistent. 


I talked with @ahbarnett on these interfaces changes, mostly we are trying to make the Julia interface consistent with Matlab and Python interfaces.  We spent a lot of time on the Matlab and Python interfaces,  so maybe they are useful to the Julia interface.  

Let me know what you think and suggestions. Since I can spent most of my time on the Julia interfaces, I'm more than happy to help with this pull request and incorporate any good pieces(anything you think is useful) into @jonas-kr pull request, and clean up the code.

Best,
Libin

**Comment by jonas-kr** [comment]
Hi @lu1and10 !
Thanks a lot for your work on this topic! I will come back to this PR next week.
Best, Jonas

**Comment by lu1and10** [comment]
Great, thank! I will make some improvements this week discussed with Alex and you can take a look next week.

Best,
Libin

**Comment by ludvigak** [comment]
Hey all, great to hear that several minds are thinking about to make sure we have a nice Julia interface. I'm not able to contribute so much myself right now, but I'll happily play the role of grumpy code reviewer =)

@jonas-kr, regarding the strided arrays - have you managed to test it?
My suspicion is that if you pass a strided view like `view(A, 1:2:N)` to the library, things will not work the way you expect them to, since the C++ interface will just be passed the base pointer

**Comment by jonas-kr** [comment]
@ludvigak Unfortunately, the `StridedArrays` work correctly only for a stride of one. I think there is no simple way to ensure that the arrays are limited to this scenario? Hence, I will probably have to undo this change.

My next step will be to have a closer look at the code by Libin so we can merge and optimize our approaches.

**Comment by ludvigak** [comment]
It is as I suspected then, so it's probably best to revert to `Array`. For strided arrays to work there would have to support for it in the core FINUFFT library, which I think it is unlikely that we would implement.

**Comment by jonas-kr** [comment]
The last few weeks have been much busier than expected, sorry for the late reply. I noticed that @lu1and10 has worked a lot on his branch implementing the guru interface. The only thing I am missing, is the adoption of multiple-dispatch. Hence, I would suggest to close this PR and create a new PR for Libin's branch first.

**Pull request closed without merging**
